// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obvmuobzgosoekfctvxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9idm11b2J6Z29zb2VrZmN0dnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDYwODQsImV4cCI6MjA2NjYyMjA4NH0.qs2g7JCl2qZe-zBvoYKdyR9fpjw1cgfvIbRJNVmGTCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);